import { Advance, OriginalityReport, ThesisPattern } from '@/types';
import { analyzeOriginality, simulateOriginalityProcessing } from '../originality-analyzer';
import { ThesisAnalyzer } from './types';

/**
 * Originality & AI Content Analyzer
 * 
 * Detects plagiarism/similarity against external sources and estimates
 * the probability that parts of the document were generated by AI.
 * 
 * Currently uses a high-quality simulator. Designed to be swapped with
 * real services like Copyleaks, Originality.ai or Turnitin.
 */
export class OriginalityAnalyzer implements ThesisAnalyzer<OriginalityReport> {
  readonly id = 'originality-ai';
  readonly name = 'Originalidad y Contenido IA';
  readonly description = 'Detecta plagio/similitud y estima probabilidad de contenido generado por IA.';

  async analyze(params: {
    advance: Advance;
    content: string;
    pattern: ThesisPattern;
    locale?: 'es' | 'en';
  }): Promise<OriginalityReport> {
    const { advance, content, locale = 'es' } = params;

    return analyzeOriginality({
      advance,
      content,
      locale,
    });
  }

  async simulateProgress(
    onProgress: (progress: number, stage: string) => void,
    locale: 'es' | 'en' = 'es'
  ): Promise<void> {
    return simulateOriginalityProcessing(onProgress, locale);
  }
}

// Singleton instance
export const originalityAnalyzer = new OriginalityAnalyzer();